//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartment()
        {
            this.HotelApartment = new HashSet<HotelApartment>();
        }
    
        public int ApartmentID { get; set; }
        public int ApartmentTypeID { get; set; }
        public int Size { get; set; }
        public int Rooms { get; set; }
        public bool HaveBreakfast { get; set; }
        public decimal Price { get; set; }
    
        public virtual ApartmentType ApartmentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelApartment> HotelApartment { get; set; }
    }
}
