//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int RatingID { get; set; }
        public int HotelID { get; set; }
        public int UserID { get; set; }
        public int Number { get; set; }
        public string Comment { get; set; }
    
        public virtual Hotel1 Hotel1 { get; set; }
        public virtual User User { get; set; }
    }
}
